# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

variables:
  PROJECT_NAME: cpm
  INSTALL_PATH: /usr/local/bin
  INSTALL_SCRIPT_NAME: install.sh
  PACKAGE_REGISTRY_BASE_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic"
  PROJECT_URL: '$PACKAGE_REGISTRY_BASE_URL/dist/$CI_COMMIT_TAG/$PROJECT_NAME-$CI_COMMIT_TAG'
  INSTALL_SCRIPT_URL: '${PACKAGE_REGISTRY_BASE_URL}/${PROJECT_NAME}/${CI_COMMIT_TAG}/${INSTALL_SCRIPT_NAME}'
  INSTALL_SCRIPT_LATEST_URL: '${PACKAGE_REGISTRY_BASE_URL}/${PROJECT_NAME}/latest/${INSTALL_SCRIPT_NAME}'

stages:
  - analysis
  - test
  - upload
  - release


analyze:
  stage: analysis
  image: gcc
  before_script:
    - apt update && apt -y install make python3 musl-dev clang
  script:
    - CC=clang make

test_and_build:
  stage: test
  image: gcc
  before_script:
    - apt update && apt -y install make python3 valgrind musl-tools musl-dev
  script:
    - gcc --version
    - make test
    - make clean
    - CC=musl-gcc make
  artifacts:
    paths:
      - './$PROJECT_NAME'

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      echo "#!/bin/sh" >> $INSTALL_SCRIPT_NAME
      echo "curl $PROJECT_URL -o $INSTALL_PATH/$PROJECT_NAME" >> $INSTALL_SCRIPT_NAME
      echo "chmod 755 $INSTALL_PATH/$PROJECT_NAME" >> $INSTALL_SCRIPT_NAME
      chmod 755 $INSTALL_SCRIPT_NAME
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_SCRIPT_NAME $INSTALL_SCRIPT_URL
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_SCRIPT_NAME $INSTALL_SCRIPT_LATEST_URL
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $PROJECT_NAME $PROJECT_URL

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Releasing $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    description: '64bit release $CI_COMMIT_TAG'
    assets:
      links:
        - name: '$INSTALL_SCRIPT_NAME'
          url: '$INSTALL_SCRIPT_URL'
        - name: '$PROJECT_NAME'
          url: '$PROJECT_URL'
