APP_NAME = cpm
VERSION = 0.0.3
INSTALL_PATH = /opt
CFLAGS += -DINSTALL_PATH=${INSTALL_PATH}

STATIC_DEP = json
SHARED_DEP =

DEPENDENCIES = Kick1911/json/0.0.2/libjson.a.1

LDFLAGS += ${STATIC_DEP:%=-l%} ${SHARED_DEP:%=-l%}
