APP_NAME = $0
VERSION = 0.0.1
INSTALL_PATH = /opt
CFLAGS += -DINSTALL_PATH=${INSTALL_PATH}
PROD_CFLAGS = -O3 -static

UNITEST_PROJECT_ID = 11728468

STATIC_DEP =
SHARED_DEP =

DEPENDENCIES += gitlab/${UNITEST_PROJECT_ID}/0.2.0

LDFLAGS += ${STATIC_DEP:%=-l%} ${SHARED_DEP:%=-l%}
