APP_NAME = cpm
VERSION = 0.0.1
INSTALL_PATH = /usr
CFLAGS += -DINSTALL_PATH=${INSTALL_PATH}

STATIC_DEP = json
SHARED_DEP =

DEPENDENCIES = https\://github.com/Kick1911/json.git

LDFLAGS += ${STATIC_DEP:%=-l%} ${SHARED_DEP:%=-l%}
