APP_NAME = $0
VERSION = 0.0.1
INSTALL_PATH = /opt
CFLAGS += -DINSTALL_PATH=${INSTALL_PATH}
PROD_CFLAGS = -O3
PROD_LDFLAGS = -static

UNITEST_PROJECT_ID = 11728468

TEST_LDFLAGS = # -lcurl
SYSTEM_DEP_ARCHIVES = # /usr/lib/x86_64-linux-gnu/libhttp_parser.a
STATIC_DEP =
SHARED_DEP =

DEPENDENCIES += gitlab/${UNITEST_PROJECT_ID}/0.3.1

LDFLAGS += ${STATIC_DEP:%=-l%} ${SHARED_DEP:%=-l%}

project: all
preprocess:

.PHONY: project
